let fPlaces = ["Switzerland", "Maldives", "Greece", "Istanbul"];
console.log("Original Order: ");
console.log(fPlaces);
console.log("\nAlphabetical Order: ");
console.log([...fPlaces].sort());
console.log("\nOriginal Order: ");
console.log(fPlaces);
console.log("\nReverse Alphabetical Order: ");
console.log([...fPlaces].sort().reverse());
console.log("\nOriginal Order: ");
console.log(fPlaces);
fPlaces.reverse();
console.log("\nReverse Order: ");
console.log(fPlaces);
fPlaces.reverse();
console.log("\nOriginal Order by Reversing: ");
console.log(fPlaces)
fPlaces.sort();
console.log("\nAlphabetical Order by Sorting: ");
console.log(fPlaces);
fPlaces.sort().reverse();
console.log("\nReverse Alphabetical order by Sorting: ");
console.log(fPlaces);