"use strict";
let x = 2;
let y = 4;
console.log("Is x > y? I predict False.");
console.log(x > y);
console.log("Is x == y? I predict False.");
console.log(x == y);
console.log("Is x >= y? I predict False.");
console.log(x >= y);
console.log("Is x <= 5 && y == 5? I predict False");
console.log(x <= 5 && y == 5);
console.log("Is x == 5 && y > 5? I predict False.");
console.log(x == 5 && y > 5);
console.log("Is x < y? I predict True.");
console.log(x < y);
console.log("Is x == 5 || y == 4? I predict True.");
console.log(x == 5 || y == 4);
console.log("Is x == 2 && y != 5? I predict True.");
console.log(x == 2 && y != 5);
console.log("Is x != y? I predict True.");
console.log(x != y);
console.log("Is x <= y? I predict True.");
console.log(x <= y);
