"use strict";
let a = 2;
let b = 4;
let c = 6;
let add = b + 4;
let sub = 14 - c;
let mul = a * b;
let div = 16 / 2;
console.log("Addition: " + add);
console.log("Subtracton: " + sub);
console.log("Multiplication: " + mul);
console.log("Division: " + div);
